services:
    api:  
        image: munafrank/portfolio-api:v1
        build:
            context: .
            dockerfile: MunaPortfolio.Api/Dockerfile
    ui:
        image: munafrank/portfolio-ui:v1
        build:
            context: .
            dockerfile: MunaPortfolio.UI/Dockerfile
        depends_on:
          - "api" 